# testing

In [1]:
# install the necessary libraries

!pip install requests beautifulsoup4 pandas --break-system-packages

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (2.31.0)
Requirement already satisfied: beautifulsoup4 in /home/elliebeynonn/.local/lib/python3.12/site-packages (4.14.3)
Requirement already satisfied: pandas in /home/elliebeynonn/.local/lib/python3.12/site-packages (3.0.2)
Requirement already satisfied: soupsieve>=1.6.1 in /home/elliebeynonn/.local/lib/python3.12/site-packages (from beautifulsoup4) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/lib/python3/dist-packages (from beautifulsoup4) (4.10.0)
Requirement already satisfied: numpy>=1.26.0 in /home/elliebeynonn/.local/lib/python3.12/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/elliebeynonn/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [2]:
# import the necessary libraries into the Jupyter notebook
    # requests: downloads the HTML of a page
    # BeautifulSoup: parses and navigates the HTML structure
    # pandas: used to analyse the data

import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

In [3]:
# Create folders in your directory to save CSVs or figures to later

import os
os.makedirs("data/raw", exist_ok = True)
os.makedirs("data/processed", exist_ok = True)
os.makedirs("figures", exist_ok = True)

In [4]:
# This is the URL of the webpage I'll be scraping for data

url = "https://worldathletics.org/stats-zone"

In [5]:
# Send a GET request to the WorldAthletics website; this is grabbing data from the website
# returns a response object which contains the HTML content of the page as a string (response.text) and the HTTP status code (tells me whether the request worked or not)

response = requests.get(url)

In [6]:
if response.status_code == 200:
    print("Request successful")
else:
    print("Request failed")

Request successful

In [7]:
# Covert the raw HTML into a structured object using BeautifulSoup

soup = BeautifulSoup(response.text, "html.parser")

In [8]:
# Extracting the data

rows = soup.find_all("pre")[0].text.split("\n")

IndexError: list index out of range

In [9]:
print(soup.find_all("pre"))

[]

In [10]:
# Unsuccessful because of the nature of the World Athletics website.

### I'm now going to scrape the [Alltime Athletics](https://www.alltime-athletics.com/) website instead of the World Athletics website.

#### Scraping for female data in the: 
* Sprint events
    * 100m
    * 200m
    * 400m
* Endurance events
    * 1500m
    * 5000m
    * 10000m

I'm going to start by only scraping one event (100m) to ensure my logic is sound

In [11]:
# Assigning the URL of the webpage I'll be scraping to a variable

url_100W = "https://www.alltime-athletics.com/w_100ok.htm"

In [12]:
# Send a HTTP GET request to Alltime Athletics

response_100W = requests.get(url_100W)

In [13]:
# Converting the raw HTML to a structured, searchable object

soup_100W = BeautifulSoup(response_100W.text, "html.parser")

In [14]:
# Creating usable data rows

pre_tag_100W = soup_100W.find("pre")

rows_100W = pre_tag_100W.text.split("\n")

In [15]:
# How many rows are there and what do they look like?

print(len(rows_100W))
print(rows_100W[:5])

3411
['', '        1      10.54      +0.9    Elaine Thompson-Herah          JAM     28.06.92    1      Eugene                     21.08.2021', '        2      10.60      +1.7    Shelly-Ann Fraser-Pryce        JAM     27.12.86    1rA    Lausanne                   26.08.2021', '        3      10.61      +1.2    Florence Griffith-Joyner       USA     21.12.59    1      Indianapolis               17.07.1988', '        3      10.61      -0.6    Elaine Thompson-Herah          JAM     28.06.92    1      Tokyo                      31.07.2021']

In [16]:
# Print the first 5 rows raw so I can see exactly what I'm working with

for row in rows_100W[:5]:
    print(repr(row))
    print(row.split())
    print()

''
[]

'        1      10.54      +0.9    Elaine Thompson-Herah          JAM     28.06.92    1      Eugene                     21.08.2021'
['1', '10.54', '+0.9', 'Elaine', 'Thompson-Herah', 'JAM', '28.06.92', '1', 'Eugene', '21.08.2021']

'        2      10.60      +1.7    Shelly-Ann Fraser-Pryce        JAM     27.12.86    1rA    Lausanne                   26.08.2021'
['2', '10.60', '+1.7', 'Shelly-Ann', 'Fraser-Pryce', 'JAM', '27.12.86', '1rA', 'Lausanne', '26.08.2021']

'        3      10.61      +1.2    Florence Griffith-Joyner       USA     21.12.59    1      Indianapolis               17.07.1988'
['3', '10.61', '+1.2', 'Florence', 'Griffith-Joyner', 'USA', '21.12.59', '1', 'Indianapolis', '17.07.1988']

'        3      10.61      -0.6    Elaine Thompson-Herah          JAM     28.06.92    1      Tokyo                      31.07.2021'
['3', '10.61', '-0.6', 'Elaine', 'Thompson-Herah', 'JAM', '28.06.92', '1', 'Tokyo', '31.07.2021']

In [17]:
# Converting rows of data into a DataFrame

data_100W = []

for row in rows_100W:
    # Split the row by spaces
    parts = row.split()
    # Skip rows without enough elements (I have 9 variables) or header rows
    if len(parts) < 9 or not parts[0].isdigit():
        continue
    try:
        # the columns I know the index of for certain
        rank = parts[0]
        mark = parts[1]
        year = parts[-1]
        # Athlete is everything between columns 3 and 5
        athlete = " ".join(parts[3:-5])
        
        data_100W.append([rank, mark, athlete, year])
    # if anything fails, skip the row and carry on
    except:
        continue

df_100W = pd.DataFrame(data_100W, columns = ["Rank", "Time", "Athlete", "Year"])

In [18]:
# Checking the structure of the DataFrame

print(df_100W.info())

<class 'pandas.DataFrame'>
RangeIndex: 3408 entries, 0 to 3407
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Rank     3408 non-null   str
 1   Time     3408 non-null   str
 2   Athlete  3408 non-null   str
 3   Year     3408 non-null   str
dtypes: str(4)
memory usage: 106.6 KB
None

In [19]:
# checking there are no nested lists

print(data_100W[:5])

[['1', '10.54', 'Elaine Thompson-Herah', '21.08.2021'], ['2', '10.60', 'Shelly-Ann Fraser-Pryce', '26.08.2021'], ['3', '10.61', 'Florence Griffith-Joyner', '17.07.1988'], ['3', '10.61', 'Elaine Thompson-Herah', '31.07.2021'], ['3', '10.61', 'Melissa Jefferson-Wooden', '14.09.2025']]

In [20]:
df_100W.head()

  Rank   Time                   Athlete        Year
0    1  10.54     Elaine Thompson-Herah  21.08.2021
1    2  10.60   Shelly-Ann Fraser-Pryce  26.08.2021
2    3  10.61  Florence Griffith-Joyner  17.07.1988
3    3  10.61     Elaine Thompson-Herah  31.07.2021
4    3  10.61  Melissa Jefferson-Wooden  14.09.2025

In [21]:
# Checking for lost data: How many rows did I lose?

#Count the number of valid rows on AllTimeAthletics
valid_rows_100W = []

for row in rows_100W:
    parts = row.split()
    if len(parts) >= 9 and parts[0].isdigit():
        valid_rows_100W.append(row)

print("Estimated valid rows:", len(valid_rows_100W))

# Compare rows before and after parsing:
print("Valid rows before parsing:", len(valid_rows_100W))
print("Successfully parsed rows:", len(data_100W))

Estimated valid rows: 3408
Valid rows before parsing: 3408
Successfully parsed rows: 3408

In [22]:
# Adding an event and gender column to be able to differentiate the rows later when I combine different events and genders into one CSV file.

df_100W["Event"] = "100m"
df_100W["Gender"] = "Female"

In [23]:
df_100W.head()

  Rank   Time                   Athlete        Year Event  Gender
0    1  10.54     Elaine Thompson-Herah  21.08.2021  100m  Female
1    2  10.60   Shelly-Ann Fraser-Pryce  26.08.2021  100m  Female
2    3  10.61  Florence Griffith-Joyner  17.07.1988  100m  Female
3    3  10.61     Elaine Thompson-Herah  31.07.2021  100m  Female
4    3  10.61  Melissa Jefferson-Wooden  14.09.2025  100m  Female

Now I'll scrape all the remaining events at the same time (200m, 400m, 1500m, 5000m and 10000m) to avoid repitition.

In [24]:
# To avoid having to repeat all these steps for each event and gender:
# Create a dictionary of all required events

eventsW = {
    "200m": "https://www.alltime-athletics.com/w_200ok.htm",
    "400m": "https://www.alltime-athletics.com/w_400ok.htm",
    "1500m": "https://www.alltime-athletics.com/w_1500ok.htm",
    "5000m": "https://www.alltime-athletics.com/w_5000ok.htm",
    "10000m": "https://www.alltime-athletics.com/w_10kok.htm"
}

In [25]:
# Create an empty list to store each event's DataFrame

dfs_W = []

In [26]:
#

for event_name, url in eventsW.items():
    print(f"Scraping {event_name}...")

    headers = {"User-Agent": "Mozilla/5.0"}
    response = requests.get(url, headers = headers, timeout = 15)
    soup = BeautifulSoup(response.text, "html.parser")
    pre = soup.find("pre")

    if pre is None:
        print(f" No data found for {event_name}, skipping")
        continue

    rows = pre.text.split("\n")
    data = []

    for row in rows:
        parts = row.split()
        if len(parts) < 9 or not parts[0].isdigit():
            continue
        try:
            rank = parts[0]
            mark = parts[1]
            year = parts[-1]
            athlete = " ".join(parts[3:-5])
            data.append([rank, mark, athlete, year])
        except:
            continue
    df_eventsW = pd.DataFrame(data, columns = ["Rank", "Time", "Athlete", "Year"])
    df_eventsW["Event"] = event_name
    df_eventsW["Gender"] = "Female"

    print(f" {len(df_eventsW)} rows scraped")
    dfs_W.append(df_eventsW)
    # Wait 2 seconds between requests to avoid overwhelming the website
    time.sleep(2)

dfW_all = pd.concat(dfs_W, ignore_index = True)
print(f"\nTotal rows: {len(dfW_all)}")

Scraping 200m...
 2727 rows scraped
Scraping 400m...
 4104 rows scraped
Scraping 1500m...
 3800 rows scraped
Scraping 5000m...
 5532 rows scraped
Scraping 10000m...
 2665 rows scraped

Total rows: 18828

In [27]:
print(dfW_all.info())

<class 'pandas.DataFrame'>
RangeIndex: 18828 entries, 0 to 18827
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Rank     18828 non-null  str
 1   Time     18828 non-null  str
 2   Athlete  18828 non-null  str
 3   Year     18828 non-null  str
 4   Event    18828 non-null  str
 5   Gender   18828 non-null  str
dtypes: str(6)
memory usage: 882.7 KB
None

In [28]:
dfW_all.head()

  Rank   Time                   Athlete        Year Event  Gender
0    1  21.34  Florence Griffith-Joyner  29.09.1988  200m  Female
1    2  21.41          Shericka Jackson  25.08.2023  200m  Female
2    3  21.45          Shericka Jackson  21.07.2022  200m  Female
3    4  21.48          Shericka Jackson  08.09.2023  200m  Female
4    5  21.53     Elaine Thompson-Herah  03.08.2021  200m  Female

In [29]:
# Combine all female event data into one large DataFrame
# I should have (3408 + 18828 = 22,236) entries

dfW_all = pd.concat([dfW_all, df_100W], ignore_index = True)

print(dfW_all.info())

<class 'pandas.DataFrame'>
RangeIndex: 22236 entries, 0 to 22235
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Rank     22236 non-null  str
 1   Time     22236 non-null  str
 2   Athlete  22236 non-null  str
 3   Year     22236 non-null  str
 4   Event    22236 non-null  str
 5   Gender   22236 non-null  str
dtypes: str(6)
memory usage: 1.0 MB
None

In [30]:
# Save the raw female data to a CSV before cleaning

dfW_all.to_csv("data/raw/female_athletics_raw.csv", index = False)

#### Scraping for male data in the: 
* Sprint events
    * 100m
    * 200m
    * 400m
* Endurance events
    * 1500m
    * 5000m
    * 10000m

In [31]:
# Create a dictionary of all event URLs

eventsM = {
    "100m": "https://www.alltime-athletics.com/m_100ok.htm",
    "200m": "https://www.alltime-athletics.com/m_200ok.htm",
    "400m": "https://www.alltime-athletics.com/m_400ok.htm",
    "1500m": "https://www.alltime-athletics.com/m_1500ok.htm",
    "5000m": "https://www.alltime-athletics.com/m_5000ok.htm",
    "10000m": "https://www.alltime-athletics.com/m_10kok.htm"
}

In [32]:
# Create an empty list to store each event's DataFrame

dfs_M = []

In [33]:
#

for event_name, url in eventsM.items():
    print(f"Scraping {event_name}...")

    headers = {"User-Agent": "Mozilla/5.0"}
    response = requests.get(url, headers = headers, timeout = 15)
    soup = BeautifulSoup(response.text, "html.parser")
    pre = soup.find("pre")

    if pre is None:
        print(f" No data found for {event_name}, skipping")
        continue

    rows = pre.text.split("\n")
    data = []

    for row in rows:
        parts = row.split()
        if len(parts) < 9 or not parts[0].isdigit():
            continue
        try:
            rank = parts[0]
            mark = parts[1]
            year = parts[-1]
            athlete = " ".join(parts[3:-5])
            data.append([rank, mark, athlete, year])
        except:
            continue
    df_eventsM = pd.DataFrame(data, columns = ["Rank", "Time", "Athlete", "Year"])
    df_eventsM["Event"] = event_name
    df_eventsM["Gender"] = "Male"

    print(f" {len(df_eventsM)} rows scraped")
    dfs_M.append(df_eventsM)
    # Wait 2 seconds between requests to avoid overwhelming the website
    time.sleep(2)

dfM_all = pd.concat(dfs_M, ignore_index = True)
print(f"\nTotal rows: {len(dfM_all)}")

Scraping 100m...
 4847 rows scraped
Scraping 200m...
 5011 rows scraped
Scraping 400m...
 5058 rows scraped
Scraping 1500m...
 11634 rows scraped
Scraping 5000m...
 9522 rows scraped
Scraping 10000m...
 10935 rows scraped

Total rows: 47007

In [34]:
dfM_all.head()

  Rank  Time      Athlete        Year Event Gender
0    1  9.58   Usain Bolt  16.08.2009  100m   Male
1    2  9.63   Usain Bolt  05.08.2012  100m   Male
2    3  9.69   Usain Bolt  16.08.2008  100m   Male
3    3  9.69    Tyson Gay  20.09.2009  100m   Male
4    3  9.69  Yohan Blake  23.08.2012  100m   Male

In [35]:
# Save the raw male data to a CSV before cleaning

dfM_all.to_csv("data/raw/male_athletics_raw.csv", index = False)

#### Combining male and female raw data into one CSV

In [36]:
# Load raw female data

df_female = pd.read_csv("data/raw/female_athletics_raw.csv")
df_female.info()

<class 'pandas.DataFrame'>
RangeIndex: 22236 entries, 0 to 22235
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Rank     22236 non-null  int64
 1   Time     22236 non-null  str
 2   Athlete  22236 non-null  str
 3   Year     22236 non-null  str
 4   Event    22236 non-null  str
 5   Gender   22236 non-null  str
dtypes: int64(1), str(5)
memory usage: 1.0 MB

In [37]:
# Create a copy of df_female

df_female_copy = df_female.copy()

In [38]:
# Load raw male data

df_male = pd.read_csv("data/raw/male_athletics_raw.csv")
df_male.info()

<class 'pandas.DataFrame'>
RangeIndex: 47007 entries, 0 to 47006
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Rank     47007 non-null  int64
 1   Time     47007 non-null  str
 2   Athlete  47007 non-null  str
 3   Year     47007 non-null  str
 4   Event    47007 non-null  str
 5   Gender   47007 non-null  str
dtypes: int64(1), str(5)
memory usage: 2.2 MB

In [39]:
# Create a copy of df_male

df_male_copy = df_male.copy()

In [40]:
# Combine both the female and male data

df_all = pd.concat([df_female_copy, df_male_copy], ignore_index = True)

In [41]:
# Should return (21715 + 46037 = 67752) entries
# this number will be wrong now ive changed the order!

df_all.info()

<class 'pandas.DataFrame'>
RangeIndex: 69243 entries, 0 to 69242
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Rank     69243 non-null  int64
 1   Time     69243 non-null  str
 2   Athlete  69243 non-null  str
 3   Year     69243 non-null  str
 4   Event    69243 non-null  str
 5   Gender   69243 non-null  str
dtypes: int64(1), str(5)
memory usage: 3.2 MB

In [42]:
# Save the complete DataFrame to CSV in the raw folder

df_all.to_csv("data/raw/athletics_complete.csv", index = False)

#### Cleaning the female data

In [ ]:
# Load the raw data CSV

dfW_raw = pd.read_csv("data/raw/female_athletics_raw.csv")
dfW_raw.info()

In [ ]:
# Create a copy of the original DataFrame

dfW_clean = dfW_raw.copy()

In [ ]:
# Convert data types within the DataFrame

# Some time values have letters as well (either from wind readings or rankings). 
# I need to clean the strings before converting to float
dfW_clean["Time"] = dfW_clean["Time"].str.extract(r"(\d+\.\d+)")
# Then convert to float
dfW_clean["Time"] = dfW_clean["Time"].astype(float)

# Values in the year colume are formatted as (e.g.) 21.08.2021.
# I need to clean the dates to only include the year
dfW_clean["Year"] = dfW_clean["Year"].str.extract(r"(\d{4})$")
# Then convert to integer
dfW_clean["Year"] = dfW_clean["Year"].astype(int)

In [ ]:
# Check this was successful

print(dfW_clean.dtypes)

In [ ]:
dfW_clean.head()

In [ ]:
dfW_clean["Event"].value_counts()

In [ ]:
# investigating if there are any duplicated data rows

dfW_clean.duplicated().sum()

In [ ]:
# Inspect the duplicated rows

dfW_clean[dfW_clean.duplicated()].head()

In [ ]:
# Remove the duplicates

dfW_clean.drop_duplicates(inplace = True)
dfW_clean.duplicated().sum()

In [ ]:
# Review .info() after dropping duplicates

dfW_clean.info()

In [ ]:
# The after dropping the duplicated rows the DataFrame has kept the original index values.
# Reset the index for cleaner data.

dfW_clean = dfW_clean.reset_index(drop = True)
dfW_clean.info()

In [ ]:
# Ensure the DataFrame is sorted by event then by year

dfW_clean.sort_values(by = ["Event", "Year"], ascending = [True, True], inplace = True)

In [ ]:
# Save the cleaned female data to a CSV

dfW_clean.to_csv("data/processed/female_athletics_clean.csv", index = False)
print("Saved cleaned data!")

#### Cleaning the male data

In [ ]:
# Load the raw data CSV

dfM_raw = pd.read_csv("data/raw/male_athletics_raw.csv")
dfM_raw.info()

In [ ]:
# Create a copy of the original DataFrame

dfM_clean = dfM_raw.copy()

In [ ]:
# Convert data types within the DataFrame

# Some time values have letters as well (either from wind readings or rankings). 
# I need to clean the strings before converting to float
dfM_clean["Time"] = dfM_clean["Time"].str.extract(r"(\d+\.\d+)")
# Then convert to float
dfM_clean["Time"] = dfM_clean["Time"].astype(float)

# Values in the year colume are formatted as (e.g.) 21.08.2021.
# I need to clean the dates to only include the year
dfM_clean["Year"] = dfM_clean["Year"].str.extract(r"(\d{4})$")
# Then convert to integer
dfM_clean["Year"] = dfM_clean["Year"].astype(int)

In [ ]:
# Check this was successful

print(dfM_clean.dtypes)

In [ ]:
dfM_clean.head()

In [ ]:
# investigating if there are any duplicated data rows

dfM_clean.duplicated().sum()

In [ ]:
# Inspect the duplicated rows

dfM_clean[dfM_clean.duplicated()].head()

In [ ]:
# Remove the duplicates

dfM_clean.drop_duplicates(inplace = True)
dfM_clean.duplicated().sum()

In [ ]:
# Review .info() after dropping duplicates

dfM_clean.info()

In [ ]:
# The after dropping the duplicated rows the DataFrame has kept the original index values.
# Reset the index for cleaner data.

dfM_clean = dfM_clean.reset_index(drop = True)
dfM_clean.info()

In [ ]:
# Ensure the DataFrame is sorted by event then by year

dfM_clean.sort_values(by = ["Event", "Year"], ascending = [True, True], inplace = True)

In [ ]:
# Save cleaned male data to CSV

dfM_clean.to_csv("data/processed/male_athletics_clean.csv", index = False)
print("Saved cleaned data!")